### ISSUE TITLE
Initial commit, initial enhancements ...

### ISSUE THREAD

**Issue by nfreear** [IET-OU/jisc-workload#1]
...
- [x] — initial commit;
- [x] — convert Readme to Markdown, add copyright, license statement, acknowledgements etc.
- [ ] — fix line-breaks `CRLF` (win) to `LF` (*nix/ os x);
- [ ] — remove trailing `?>` from PHP files;
- [x] — maybe add `composer.json`, with php-lint, PSR-2 sniffing etc.?
- [x] — [`.travis.yml`](https://travis-ci.org/IET-OU/jisc-workload)
- [ ] — maybe switch to [dotenv](https://github.com/vlucas/phpdotenv) for configuration?
- [x] — Google Analytics, bug #2;
- [x] — web-root portability, bug #4;
- [x] — accessibility fixes, bug #4;
- ...?

---
